const oceanLinesObj = {
    ACL : {nameZh:'大西洋集装箱航运', nameEn:'Atlantic Container Line', pageUrl:'https://www.aclcargo.com/trackCargo.php?search_for=containerNumber'},
    ONE : {nameZh:'海洋网联船务', nameEn:'Ocean Network Express', pageUrl:'https://ecomm.one-line.com/ecom/CUP_HOM_3301.do'},
    Textainer : {nameZh:'美国天泰集装箱租赁集团', nameEn:'Textainer Group', pageUrl:'', rental:'http://tex.textainer.com/Equipment/StatusAndSpecificationsInquiry.aspx'},
    APL : {nameZh:'美国总统轮船', nameEn:'American President Lines', pageUrl:'https://www.apl.com/ebusiness/tracking/search?SearchBy=Container&Reference=containerNumber'},
    MSK : {nameZh:'马士基', nameEn:'Maersk Lines', pageUrl:'https://www.maersk.com.cn/tracking/#tracking/containerNumber'},
    Beacon : {nameZh:'Beacon集装箱租赁', nameEn:'Beacon Intermodal', pageUrl:'', rental:'https://beacon.intermodalportal.com/'},
    Bridgehead : {nameZh:'Bridgehead集装箱租赁', nameEn:'Bridgehead Containers', pageUrl:'http://www.bridgeheadcontainers.com/onhire.asp?contNO=containerNumber&Submit=Search&FindCont=1'},
    BlueSky : {nameZh:'Blue Sky集装箱租赁', nameEn:'Blue Sky Intermodal', pageUrl:'', rental:'https://bluesky.intermodalportal.com/'},
    CAI : {nameZh:'CAI集装箱租赁', nameEn:'CAI International', pageUrl:'', rental:'https://www.capps.com/cgi-bin/publicUnitInfo?UNIT=containerNumber'},
    HapagLloyd : {nameZh:'赫伯罗特股份公司', nameEn:'HAPAG-LLOYD AG', pageUrl:'https://www.hapag-lloyd.com/en/online-business/tracing/tracing-by-container.html?container=containerNumber'},
    CARU : {nameZh:'CARU集装箱租赁', nameEn:'CARU Container',pageUrl:'',rental:'https://portal.carucontainers.com/scripts/caruweb02.wsc/WService=caru/system/web/sp-web-menu.r?program=DP.WEB-UNIT_INQUIRY&containernumber=containerNumber&Submit=Open'},
    COSCO : {nameZh:'中远海运集装箱运输有限公司', nameEn:'Cosco Shipping Lines Co.,LTD', pageUrl:'https://elines.coscoshipping.com/ebusiness/cargoTracking?trackingType=CONTAINER&number=containerNumber'},
    Hamburg : {nameZh:'汉堡南美船务集团', nameEn:'Hamburg Süd Group', pageUrl:'https://www.hamburgsud-line.com/liner/en/liner_services/ecommerce/track_trace/index.html'},
    CMA : {nameZh:'法国达飞海运集团', nameEn:'CMA CGM SHIPPING CO.,LTD.', pageUrl:'https://www.cma-cgm.com/ebusiness/tracking/search?SearchBy=Container&Reference=containerNumber'},
    Marguisa : {nameZh:'Marguisa', nameEn:'Marguisa', pageUrl:'https://tracking.marguisa.com/'},
    Seaco : {nameZh:'Seaco集装箱租赁', nameEn:'Seaco Global', pageUrl:'', rental:'https://newseaweb.seacoglobal.com/sap/bc/ui5_ui5/sap/zseaco_ue15/index.html'},
    GCX : {nameZh:'Global Container集装箱租赁', nameEn:'Global Container International', pageUrl:'', rental:'https://gcx.intermodalportal.com/'},
    Safmarine : {nameZh:'萨非航运', nameEn:'Safmarine Container Lines N.V.', pageUrl:'https://www.safmarine.com/tracking/#tracking/containerNumber'},
    Crowley : {nameZh:'克罗利海运集团', nameEn:'Crowley Maritime Corporation', pageUrl:'https://www.crowley.com/liner-shipment-tracking/'},
    CNCA : {nameZh:'加拿大国家铁路', nameEn:'Canadian National Railway', pageUrl:'https://www.cn.ca/en/customer-centre/tools/intermodal-international/'},
    Seacube : {nameZh:'Seacube集装箱租赁', nameEn:'Seacube Containers', pageUrl:'', rental:'https://seacube.intermodalportal.com/'},
    Florens : {nameZh:'Florens集装箱租赁', nameEn:'Florens container services', pageUrl:'', rental:'https://www.florens.com/equipment#/unit-inquiry'},
    Evergreen : {nameZh:'长荣海运', nameEn:'Evergreen Marine Corp.', pageUrl:'https://www.shipmentlink.com/servlet/TDB1_CargoTracking.do'},
    Emirate : {nameZh:'阿联酋航运', nameEn:'Emirates Shipping Line', pageUrl:'https://www.emiratesline.com/cargo-tracking/'},
    Fesco : {nameZh:'俄罗斯远东海洋轮船公司', nameEn:'Far-Eastern Shipping Company Ltd.', pageUrl:'https://www.fesco.ru/en/clients/tracking/?codes=containerNumber'},
    Grimaldi : {nameZh:'意大利格里马尔迪集团', nameEn:'Grimaldi Lines', pageUrl:'https://www.net.grimaldi.co.uk/GNET45/Pages_GAtlas/WFContainerTracking'},
    Touax : {nameZh:'Touax集装箱租赁', nameEn:'Touax Container Solutions', pageUrl:'', rental:'http://www.touax-container.com/unit-inquiry'},
    UES : {nameZh:'UES国际（香港）控股有限公司', nameEn:'UESInternational（HK）Holdings Limited', pageUrl:'http://www.ueshk.com/phone/inquiries_detail.aspx?classid=3&aid=5&leftid=18&seachstr=containerNumber'},
    HMM : {nameZh:'现代商船', nameEn:'Hyundai Merchant Marine Co., Ltd', pageUrl:'http://www.hmm21.com/cms/business/ebiz/trackTrace/trackTrace/index.jsp?type=2&number=containerNumber&is_quick=Y&quick_params='},
    Matson : {nameZh:'美国美森轮船', nameEn:'Matson Ship', pageUrl:'https://www.matson.com/shipment-tracking.html'},
    Triton : {nameZh:'特里同集装箱租赁', nameEn:'Triton Container', pageUrl:'', rental:'https://www.trtn.com/tritoncontainer/unitStatus/show/containerNumber'},
    Italia : {nameZh:'意大利海运股份有限公司', nameEn:'Italia Marittima S.p.A', pageUrl:'https://www.shipmentlink.com/servlet/TDB1_CargoTracking.do'},
    MSC : {nameZh:'地中海航运公司', nameEn:'Mediterranean Shipping Cpmpany S.A.', pageUrl:'https://www.msc.com/track-a-shipment'},
    MACS : {nameZh:'MACS航运', nameEn:'MACS Maritime Carrier Shipping', pageUrl:'https://www.macship.com/E-BUSINESS/Tracking-And-Tracing'},
    NileDutch : {nameZh:'尼罗河荷兰人非洲航运公司', nameEn:'Nile Dutch Africa Line BV', pageUrl:'https://www.niledutch.com/en/schedules-tracking/track-your-container/'},
    PIL : {nameZh:'太平船务有限公司', nameEn:'Pacific International Lines(PTE) Ltd', pageUrl:'https://www.pilship.com/cn-our-track-and-trace-pil-pacific-international-lines/120.html?lang=cn'},
    Sinotrans : {nameZh:'中外运集装箱运输有限公司', nameEn:'Sinotrans Container Lines Co.,Ltd', pageUrl:'http://ebusiness.sinolines.com.cn/snlebusiness/TrackingCargoByBlnoE.aspx?subject=cntrno&item=containerNumber'},
    PAN : {nameZh:'泛洋海运', nameEn:'Pan Ocean Shipping Co.,Ltd', pageUrl:'http://container.panocean.com/HP2401/hp2401List.stx'},
    TrailerBridge : {nameZh:'Trailer Bridge', nameEn:'Trailer Bridge', pageUrl:'http://legacy.trailerbridge.com/CustomerInquiry/CI.aspx'},
    Turkon : {nameZh:'Turkon Line', nameEn:'Turkon Line', pageUrl:'https://www.turkon.com/en/Container-Tracking.aspx?p=1&cont=containerNumber'},
    WanHai : {nameZh:'万海航运股份有限公司', nameEn:'Wan Hai Lines Ltd', pageUrl:'https://cn.wanhai.com/views/quick/cargo_tracking.xhtml'},
    YML : {nameZh:'阳明海运股份有限公司', nameEn:'Yang Ming Marine Transport Corp', pageUrl:'https://www.yangming.com/e-service/Track_Trace/track_trace_cargo_tracking.aspx'},
    ZIM : {nameZh:'以星综合航运服务有限公司', nameEn:'ZIM Integrated Shipping Services Ltd', pageUrl:'https://www.zimchina.com/tools/track-a-shipment'},
    OOCL : {nameZh:'东方海外货柜航运有限公司', nameEn:'Orient Overseas Container Line', pageUrl:'https://moc.oocl.com/party/cargotracking/ct_search_from_other_domain.jsf?ANONYMOUS_BEHAVIOR=BUILD_UP&domainName=PARTY_DOMAIN&ENTRY_TYPE=OOCL&ENTRY=MCC&ctSearchType=CNTR&ctShipmentNumber=containerNumber'},
    RCL : {nameZh:'泰国宏海箱运有限公司', nameEn:'Regional Container Lines', pageUrl:'https://www.rclgroup.com/Home#cargo'},
    CRCTC : {nameZh:'中国铁路', nameEn:'China Railway Container Transoprt Corp', pageUrl:'http://hyfw.95306.cn/gateway/DzswD2D/Dzsw/page/business-chcx-hwzzsy?type=jzx#tabs-5'},
};

let oceanLineList = {
    ACLU:oceanLinesObj.ACL,
    AKLU:oceanLinesObj.ONE,
    AMFU:oceanLinesObj.Textainer,
    AMZU:oceanLinesObj.Textainer,
    APHU:oceanLinesObj.APL,
    APLS:oceanLinesObj.APL,
    APLU:oceanLinesObj.APL,
    APMU:oceanLinesObj.MSK,
    APRU:oceanLinesObj.APL,
    APZU:oceanLinesObj.APL,
    AXIU:oceanLinesObj.Textainer,
    AZLU:oceanLinesObj.HapagLloyd,
    BEAU:oceanLinesObj.Beacon,
    BHCU:oceanLinesObj.Bridgehead,
    BMOU:oceanLinesObj.Beacon,
    BSIU:oceanLinesObj.BlueSky,
    CAAU:oceanLinesObj.CAI,
    CADU:oceanLinesObj.Hamburg,
    CAIU:oceanLinesObj.CAI,
    CARU:oceanLinesObj.CARU,
    CATU:oceanLinesObj.CARU,
    CAXU:oceanLinesObj.CAI,
    CASU:oceanLinesObj.HapagLloyd,
    CBHU:oceanLinesObj.COSCO,
    CCLU:oceanLinesObj.COSCO,
    CGTU:oceanLinesObj.CMA,
    CHIU:oceanLinesObj.Textainer,
    CHLU:oceanLinesObj.Marguisa,
    CLHU:oceanLinesObj.Textainer,
    CMAU:oceanLinesObj.CMA,
    CMBU:oceanLinesObj.Safmarine,
    CMCU:oceanLinesObj.Crowley,
    CMUU:oceanLinesObj.HapagLloyd,
    CNEU:oceanLinesObj.CAI,
    CNIU:oceanLinesObj.Hamburg,
    CNRU:oceanLinesObj.CNCA,
    CPSU:oceanLinesObj.HapagLloyd,
    CRLU:oceanLinesObj.Seacube,
    CRSU:oceanLinesObj.Seaco,
    CRXU:oceanLinesObj.Seaco,
    CSLU:oceanLinesObj.COSCO,
    CSNU:oceanLinesObj.COSCO,
    CSQU:oceanLinesObj.HapagLloyd,
    CXDU:oceanLinesObj.Seaco,
    DFSU:oceanLinesObj.Florens,
    DRYU:oceanLinesObj.Seacube,
    DVRU:oceanLinesObj.CMA,
    ECMU:oceanLinesObj.CMA,
    EISU:oceanLinesObj.Evergreen,
    EITU:oceanLinesObj.Evergreen,
    EKLU:oceanLinesObj.ONE,
    EMCU:oceanLinesObj.Evergreen,
    ESPU:oceanLinesObj.Emirate,
    ESSU:oceanLinesObj.ONE,
    FBIU:oceanLinesObj.Florens,
    FBLU:oceanLinesObj.Florens,
    FCIU:oceanLinesObj.Florens,
    FCLU:oceanLinesObj.Florens,
    FDCU:oceanLinesObj.Florens,
    FESU:oceanLinesObj.Fesco,
    FFAU:oceanLinesObj.Florens,
    FRLU:oceanLinesObj.MSK,
    FSCU:oceanLinesObj.Florens,
    GATU:oceanLinesObj.Textainer,
    GCEU:oceanLinesObj.Seaco,
    GCNU:oceanLinesObj.Grimaldi,
    GCXU:oceanLinesObj.GCX,
    GESU:oceanLinesObj.Seaco,
    GLDU:oceanLinesObj.Touax,
    GSTU:oceanLinesObj.Seaco,
    GVCU:oceanLinesObj.UES,
    GVDU:oceanLinesObj.UES,
    HAMU:oceanLinesObj.HapagLloyd,
    HASU:oceanLinesObj.Hamburg,
    HDMU:oceanLinesObj.HMM,
    HLCU:oceanLinesObj.HapagLloyd,
    HLXU:oceanLinesObj.HapagLloyd,
    HMCU:oceanLinesObj.Evergreen,
    HNKU:oceanLinesObj.Textainer,
    HNSU:oceanLinesObj.Triton,
    HRZU:oceanLinesObj.Matson,
    ICSU:oceanLinesObj.Triton,
    IEAU:oceanLinesObj.Seaco,
    IMTU:oceanLinesObj.Italia,
    INBU:oceanLinesObj.Seacube,
    INKU:oceanLinesObj.Seacube,
    INNU:oceanLinesObj.Seacube,
    IPXU:oceanLinesObj.Seacube,
    IRNU:oceanLinesObj.Seacube,
    ITAU:oceanLinesObj.HapagLloyd,
    ITLU:oceanLinesObj.Seaco,
    IVLU:oceanLinesObj.HapagLloyd,
    KHJU:oceanLinesObj.Hamburg,
    KHLU:oceanLinesObj.Hamburg,
    KKFU:oceanLinesObj.ONE,
    KKTU:oceanLinesObj.ONE,
    KLFU:oceanLinesObj.ONE,
    KLTU:oceanLinesObj.ONE,
    KNLU:oceanLinesObj.MSK,
    LTIU:oceanLinesObj.Italia,
    MAEU:oceanLinesObj.MSK,
    MAGU:oceanLinesObj.Textainer,
    MARU:oceanLinesObj.CARU,
    MATS:oceanLinesObj.Matson,
    MATU:oceanLinesObj.Matson,
    MAXU:oceanLinesObj.Textainer,
    MBIU:oceanLinesObj.Bridgehead,
    MEDU:oceanLinesObj.MSC,
    MGLU:oceanLinesObj.Textainer,
    MIEU:oceanLinesObj.MSK,
    MLCU:oceanLinesObj.Textainer,
    MMCU:oceanLinesObj.CMA,
    MNBU:oceanLinesObj.MSK,
    MOAU:oceanLinesObj.ONE,
    MOCU:oceanLinesObj.MACS,
    MOEU:oceanLinesObj.ONE,
    MOFU:oceanLinesObj.ONE,
    MOGU:oceanLinesObj.ONE,
    MOLU:oceanLinesObj.ONE,
    MORU:oceanLinesObj.ONE,
    MOSU:oceanLinesObj.ONE,
    MOTU:oceanLinesObj.ONE,
    MRKU:oceanLinesObj.MSK,
    MRSU:oceanLinesObj.MSK,
    MSCU:oceanLinesObj.MSC,
    MSDU:oceanLinesObj.MSC,
    MSKU:oceanLinesObj.MSK,
    MSMU:oceanLinesObj.MSC,
    MWCU:oceanLinesObj.MSK,
    MWMU:oceanLinesObj.MSK,
    NDSU:oceanLinesObj.NileDutch,
    NEPU:oceanLinesObj.APL,
    NOLU:oceanLinesObj.APL,
    NOSU:oceanLinesObj.APL,
    NYKU:oceanLinesObj.ONE,
    OCLU:oceanLinesObj.MSK,
    OCGU:oceanLinesObj.Textainer,
    ONEU:oceanLinesObj.ONE,
    OOCU:oceanLinesObj.OOCL,
    OOLU:oceanLinesObj.OOCL,
    PCIU:oceanLinesObj.PIL,
    POCU:oceanLinesObj.MSK,
    PONU:oceanLinesObj.MSK,
    PRSU:oceanLinesObj.Textainer,
    REGU:oceanLinesObj.RCL,
    SCMU:oceanLinesObj.MSK,
    SCXU:oceanLinesObj.Seaco,
    SCZU:oceanLinesObj.Seaco,
    SEAT:oceanLinesObj.MSK,
    SEAU:oceanLinesObj.MSK,
    SEGU:oceanLinesObj.Seaco,
    SKYU:oceanLinesObj.CAI,
    SLSU:oceanLinesObj.CNCA,
    SMLU:oceanLinesObj.Sinotrans,
    STXU:oceanLinesObj.PAN,
    SUDU:oceanLinesObj.Hamburg,
    TBJU:oceanLinesObj.CRCTC,
    TCKU:oceanLinesObj.Triton,
    TCLU:oceanLinesObj.Triton,
    TCNU:oceanLinesObj.Triton,
    TEXU:oceanLinesObj.Textainer,
    TEMU:oceanLinesObj.Textainer,
    TGBU:oceanLinesObj.Textainer,
    TGCU:oceanLinesObj.Touax,
    TGHU:oceanLinesObj.Textainer,
    TMMU:oceanLinesObj.Hamburg,
    TOLU:oceanLinesObj.Triton,
    TORU:oceanLinesObj.MSK,
    TPHU:oceanLinesObj.Triton,
    TPXU:oceanLinesObj.Triton,
    TRBU:oceanLinesObj.TrailerBridge,
    TRDU:oceanLinesObj.Triton,
    TRHU:oceanLinesObj.Triton,
    TRIU:oceanLinesObj.Triton,
    TRKU:oceanLinesObj.Turkon,
    TRLU:oceanLinesObj.Triton,
    TTLU:oceanLinesObj.Triton,
    TTNA:oceanLinesObj.Triton,
    TTNU:oceanLinesObj.Triton,
    UACU:oceanLinesObj.HapagLloyd,
    UESU:oceanLinesObj.UES,
    UETU:oceanLinesObj.UES,
    UGMU:oceanLinesObj.Evergreen,
    UXXU:oceanLinesObj.UES,
    WBPU:oceanLinesObj.Seacube,
    WCIU:oceanLinesObj.Textainer,
    WHLU:oceanLinesObj.WanHai,
    WSCU:oceanLinesObj.CARU,
    XINU:oceanLinesObj.Textainer,
    XTRU:oceanLinesObj.Seaco,
    YMLU:oceanLinesObj.YML,
    YMLY:oceanLinesObj.YML,
    ZCSU:oceanLinesObj.ZIM,
    ZIMU:oceanLinesObj.ZIM,
};

exports.oceanLineList = oceanLineList;
exports.oceanLinesObj = oceanLinesObj;